'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.4927
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Import_Planifier_IM.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _58() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("58", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7trio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7trio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property accepter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accepter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_1611() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_1611", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property agt_action_success() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("agt_action_success", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AnalyzeWizard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AnalyzeWizard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AnalyzeWizard1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AnalyzeWizard1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AnalyzeWizard11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AnalyzeWizard11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AnalyzeWizard2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AnalyzeWizard2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property applications_161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("applications_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowback_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowback_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowdown_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowdown_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowforward_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowforward_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowforward_161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowforward_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowforward_1611() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowforward_1611", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowforward_162() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowforward_162", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowforward_163() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowforward_163", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowup_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowup_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Backup_and_Restore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Backup and Restore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property banner_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property banner_module_waza1222507595() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_module_waza1222507595", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bannière_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bannière 1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property billetage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("billetage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btAjouter22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btAjouter22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btEnregistrer22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btEnregistrer22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btFermer22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btFermer22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btFermer221() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btFermer221", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btFermer222() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btFermer222", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRepertoireB22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRepertoireB22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRepertoireB221() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRepertoireB221", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btSupprimer22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btSupprimer22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btSupprimer221() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btSupprimer221", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Checked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Checked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property create() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("create", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property create1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("create1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Creer1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Creer1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property criticalind_status() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("criticalind_status", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property display() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("display", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property documents_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("documents_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exlamation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exlamation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property export1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property export11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exportcsv1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exportcsv1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exportcsv11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exportcsv11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fichiers_ini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fichiers ini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fleche() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fleche", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property foldeopen_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("foldeopen_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property foldeopen_161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("foldeopen_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Image_5_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image_5_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image019() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image019", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image020() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image020", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image033() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image033", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image034() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image034", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Image2_Image1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image2_Image1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property k1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("k1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property k2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("k2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kworldclock1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kworldclock1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property newSp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newSp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tServer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tServer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
